apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm-repository.yaml
- namespace.yaml
- oauth-secret.yaml
- helm-release.yaml

commonLabels:
  app.kubernetes.io/name: tailscale-operator
  app.kubernetes.io/part-of: tailscale
  app.kubernetes.io/component: operator