apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app/namespace.yaml
- app/crds.yaml
- app/operator.yaml

namespace: tailscale-system

commonLabels:
  app.kubernetes.io/name: tailscale-operator
  app.kubernetes.io/part-of: tailscale
  app.kubernetes.io/component: operator