apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    name: tailscale
    # Required for Tailscale operator to function properly
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged