apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dknathalage/cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cluster
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./apps/local/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./apps/local/env/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./apps/local/env/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
