apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: "1.14.5"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    domainFilters:
      - dknathalage.dev
    policy: upsert-only
    sources:
      - service
      - ingress
    registry: txt
    txtOwnerId: external-dns
    txtPrefix: "external-dns-"
    logLevel: info
    serviceMonitor:
      enabled: false
    rbac:
      create: true
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi