# Private Service Template with Private Subdomain
# Usage: Copy this template and replace <SERVICE_NAME> with your actual service name
# Uses private.dknathalage.dev subdomain for family services
apiVersion: v1
kind: Service
metadata:
  name: <SERVICE_NAME>-tailscale
  annotations:
    # Tailscale configuration
    tailscale.com/expose: "true"
    # No funnel annotation - private access only
    tailscale.com/hostname: "<SERVICE_NAME>"
    tailscale.com/tags: "tag:k8s,tag:private,tag:family"
    
    # External-DNS for private subdomain resolution
    external-dns.alpha.kubernetes.io/hostname: "<SERVICE_NAME>.private.dknathalage.dev"
    external-dns.alpha.kubernetes.io/target: "<SERVICE_NAME>.tail2af8c3.ts.net"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app: <SERVICE_NAME>
    tier: private
    dns-strategy: private-subdomain
spec:
  selector:
    app: <SERVICE_NAME>
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP