# Tailscale-enabled version of simple-frontend service
# This will be exposed via Tailscale Funnel for public access
# DNS: Automatically managed by External-DNS
apiVersion: v1
kind: Service
metadata:
  name: simple-frontend-tailscale
  annotations:
    # Tailscale configuration
    tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
    tailscale.com/hostname: "frontend"
    tailscale.com/tags: "tag:k8s,tag:public"
    
    # External-DNS automatic DNS management
    external-dns.alpha.kubernetes.io/hostname: "frontend.dknathalage.dev"
    external-dns.alpha.kubernetes.io/target: "frontend.tail2af8c3.ts.net"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"  # Enable Cloudflare proxy for public services
  labels:
    app: simple-frontend
    tier: public
    dns-strategy: automatic
spec:
  selector:
    app: simple-frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP