# Tailscale Kubernetes Operator
# Based on: https://github.com/tailscale/tailscale/tree/main/cmd/k8s-operator

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-operator
  namespace: tailscale-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-operator
rules:
- apiGroups: [""]
  resources: ["events", "services", "services/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tailscale.com"]
  resources: ["connectors", "proxyclasses", "dnsconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["tailscale.com"]
  resources: ["connectors/status", "dnsconfigs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-operator
subjects:
- kind: ServiceAccount
  name: tailscale-operator
  namespace: tailscale-system

---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale-system
stringData:
  # This needs to be filled with your OAuth credentials
  # Instructions will be provided in the migration guide
  client_id: "REPLACE_WITH_YOUR_CLIENT_ID"
  client_secret: "REPLACE_WITH_YOUR_CLIENT_SECRET"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-operator
  namespace: tailscale-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-operator
  template:
    metadata:
      labels:
        app: tailscale-operator
    spec:
      serviceAccountName: tailscale-operator
      containers:
      - name: operator
        image: tailscale/k8s-operator:latest
        env:
        - name: OPERATOR_HOSTNAME
          value: "tailscale-operator"
        - name: OPERATOR_SECRET
          value: "operator-oauth"
        - name: OPERATOR_LOGGING
          value: "info"
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENT_ID_FILE
          value: "/oauth/client_id"
        - name: CLIENT_SECRET_FILE
          value: "/oauth/client_secret"
        - name: PROXY_IMAGE
          value: "tailscale/tailscale:latest"
        - name: PROXY_TAGS
          value: "tag:k8s"
        - name: APISERVER_PROXY
          value: "false"
        - name: PROXY_FIREWALL_MODE
          value: "auto"
        volumeMounts:
        - name: oauth
          mountPath: "/oauth"
          readOnly: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: oauth
        secret:
          secretName: operator-oauth